export type WeatherConditionType =
  | 'clearDay'
  | 'clearNight'
  | 'cloudy'
  | 'partlyCloudyDay'
  | 'partlyCloudyNight'
  | 'partialMoon'
  | 'cloudyPartialMoon'
  | 'rain'
  | 'partlySunnyRain'
  | 'partlyMoonyRain'
  | 'heavyRain'
  | 'thunderstorm'
  | 'snow'
  | 'heavySnow'
  | 'wind'
  | 'unknown'
;
