export default {
  REQUEST_POSTS: 'REQUEST_POSTS',
  LOAD_POSTS: 'LOAD_POSTS',
  LOAD_POST: 'LOAD_POST',
  POSTS_LOADED: 'POSTS_LOADED',
  REQUEST_POSTS_FAILURE: 'REQUEST_POSTS_FAILURE',
  POST_REQUEST_FAILURE: 'POST_REQUEST_FAILURE',
  REFRESH_FEED: 'REFRESH_FEED',
  UPVOTE: 'UPVOTE',
  UPVOTE_FAILURE: 'UPVOTE_FAILURE'
};
